Import('currentenv librarydir corelibtargets binarydir')

import os

getkeystring     = currentenv.SharedLibrary(os.path.join(binarydir, 'bin/Release/plugin/getkeystring'), ['getkeystring.cpp'], LIBS = ['v8'])
Depends(getkeystring, corelibtargets)
