Import('currentenv librarydir corelibtargets binarydir LibraryInstall')

import os

getkeystring     = currentenv.SharedLibrary('getkeystring', ['getkeystring.cpp'], LIBS = ['v8'])
Depends(getkeystring, corelibtargets)

LibraryInstall(os.path.join(binarydir, 'plugin'), getkeystring, currentenv)
