Import('currentenv librarydir corelibtargets binarydir')

import os

audioBASS_files	 = ['frontend.cpp', 'bass_backend.cpp', 'script.cpp']
audioBASS_libs	 = ['bass', 'bassmidi']

audioBASS     = currentenv.SharedLibrary(os.path.join(binarydir, 'bin/Release/plugin/audioBASS'), audioBASS_files, LIBS = ['t5', 'configmanager', 'v8', audioBASS_libs])
Depends(audioBASS, corelibtargets)
