import os
import sys

full_import_list ="globalenv localenv IsLinux IsWindows IsDarwin LibraryInstall compiler librarydir binarydir component"

Import(full_import_list)

files = ["opengame.cpp", "openscript.cpp"]

graphicalg = globalenv.SharedLibrary('graphicalg', 'structures.cpp')

installdir = os.path.join(os.path.join(librarydir, component))

LibraryInstall(installdir, graphicalg, globalenv)
globalenv.Install(os.path.join(installdir, "include"), ["structures.h"])

Return("graphicalg")
