import os
import sys

full_import_list ="globalenv localenv IsLinux IsWindows IsDarwin LibraryInstall compiler librarydir binarydir component"

Import(full_import_list)

graphicalg = globalenv.SharedLibrary("graphicalg", ["structures.cpp", "circles.c", "lines.c"])

installdir = os.path.join(os.path.join(librarydir, component))

LibraryInstall(installdir, graphicalg, globalenv)
globalenv.Install(os.path.join(installdir, "include"), ["structures.h", "circles.h", "lines.h", "graphicalg_stub.h"])

Return("graphicalg")
