Import('currentenv librarydir corelibtargets binarydir LibraryInstall jslib')

import os
import glob

inputSDL2_files = glob.glob("*.cpp")

inputSDL2 = currentenv.SharedLibrary('inputSDL2', inputSDL2_files, LIBS = ['t5', 'configmanager', jslib, 'SDL2'])
Depends(inputSDL2, corelibtargets)

LibraryInstall(os.path.join(binarydir, 'plugin'), inputSDL2, currentenv)
