Import('currentenv librarydir corelibtargets binarydir')

import os
import glob

Sapphire_files	 = glob.glob("*.cpp") + glob.glob("Galileo/*.cpp")

Sapphire     = currentenv.SharedLibrary("Sapphire", Sapphire_files,
  LIBS = ['t5', 'graphiccommon', 'graphicalg', 'configmanager', 'v8', 'SDL2'],
  FRAMEWORKS = ['SDL2_image', ['OpenGL']] )
Depends(Sapphire, corelibtargets)
