import os
import sys

Import("environment")

yyymonitor_files = ["monitor.cpp"]

conf = Configure(environment)

if conf.CheckCHeader("pthread.h"):
  yyymonitor_files += ["monitor_pthread.c"]
elif sys.platform.startswith('win'):
  yyymonitor_files += ["monitor_win32.c"]
  
libyyymonitor = environment.StaticLibrary("yyymonitor", yyymonitor_files)

Return("libyyymonitor")
