import os
import sys
import glob

full_import_list ="globalenv localenv IsLinux IsWindows IsDarwin compiler librarydir binarydir jslib"

Import(full_import_list)

engine_files = [
    "engine.cpp",
    "loadplugin.cpp",
    "intrinsics.cpp"
]

localenv = globalenv.Clone()
localenv.Append(LIBS = ['t5', jslib, 'configmanager'])

turbosphere = localenv.Program("turbosphere", source = engine_files)

globalenv.Install(binarydir, [turbosphere])

Return("turbosphere")

