Import('currentenv IsDarwin IsWindows IsLinux IsSolaris')

import os
import sys

platform_files = ["sm_wrapper.cpp"]
platform_libs = []
platform_frameworks = []

if IsDarwin():
    platform_files += ["osx_gettime.m"]
    platform_frameworks = ["CoreServices"]
elif IsWindows():
    platform_files += ["win32_time.c"]
elif IsSolaris(): #Also works with AIX
    platform_files += ["solaris_gettime.c"]

if os.name == "posix":
    platform_files += ["unix_sleep.c"]


chrono_platform = currentenv.StaticLibrary('chrono_platform', platform_files, LIBS = platform_libs, FRAMEWORKS = platform_frameworks)
Return('chrono_platform')
