import os
import sys

full_import_list ="globalenv localenv IsLinux IsWindows IsDarwin compiler librarydir binarydir component"

Import(full_import_list)

t5 = globalenv.SharedLibrary('t5', 't5.cpp')

installdir = os.path.join(os.path.join(librarydir, component))

globalenv.Install(installdir, [t5])
globalenv.Install(os.path.join(installdir, "include"), ["t5.h"], CPPDEFINES = "PREFER_STAT")

Return("t5")
