import os
import sys

full_import_list ="globalenv localenv IsLinux IsWindows IsDarwin compiler librarydir binarydir component"

Import(full_import_list)

files = ["screen.cpp", "color.cpp"]

graphiccommon = globalenv.SharedLibrary('../graphiccommon', files)

installdir = os.path.join(os.path.join(librarydir, component))

globalenv.Install(installdir, graphiccommon)

globalenv.Install(os.path.join(installdir, "include"), ["color.h", "screen.h"])

Return("graphiccommon")
